### ISSUE TITLE
Style the “changed” comments

### ISSUE THREAD

**Issue by antonlegoo** [myfossil/myfossil-theme#120]
Style the “changed” comments. Example: http://dev.myfossil.org/fossils/380/

![screen shot 2015-01-08 at 9 37 51 am](https://cloud.githubusercontent.com/assets/1424526/5667118/115299fc-971a-11e4-9623-b41d4a5d2d1a.png)

**Comment by woodb** [comment]
Awesome, I've been hoping to get these looking better. 

The HTML used can be found at:
https://github.com/myfossil/myfossil-specimen/tree/master/public/templates/activities

**Comment by antonlegoo** [comment]
Brandon, thanks for the pointer.

"Changed" activities now appear like the screenshot below.

![screen shot 2015-01-09 at 10 42 10 am](https://cloud.githubusercontent.com/assets/1424526/5685491/806181fc-97ef-11e4-8192-4b767ea57eb4.png)
