### ISSUE TITLE
Homepage redesign

### ISSUE THREAD

**Issue by woodb** [myfossil/myfossil-theme#149]

**Comment by msh1411** [comment]
Hi, I'd be willing to help with the design, I only design though, I can't code yet. My design portfolio is at https://dribbble.com/mshanda

**Comment by woodb** [comment]
Hey @msh1411, that'd be super rad!

We're wanting to emphasize some new themes and get people excited about myFOSSIL. 

Let me know what you think, we'd love to hear your ideas!

Here's what we have so far...
![image](https://cloud.githubusercontent.com/assets/1631487/6210400/60d60e68-b59d-11e4-8c9d-a7ac517b0a47.png)
![image](https://cloud.githubusercontent.com/assets/1631487/6210402/6fb3f332-b59d-11e4-80a5-d9eabc8f08bb.png)

**Comment by woodb** [comment]
Also, no worries about not being able to code, that's what I'm here for :whale2:

**Comment by msh1411** [comment]
Sorry for not getting back you, I completely forgot. The design so far looks pretty solid I don't think it needs much work to be honest. I'll have to think about where it can be improved, what program/app was the current design made in?, I use Sketch.

**Comment by woodb** [comment]
Hey @msh1411, so glad to hear from you!

We're in the middle of planning how we can make this page way way better, which could mean starting with a new design altogether! Our main focus is on getting people excited about myFOSSIL enough to sign up and join the discussion.

Anything that you could contribute would be hugely appreciated, even if it's as small as an icon!

Creative input on how we can communicate the value of growing the myFOSSIL community among paleontologists, amateur and professional alike is really where we're hurting right now on this one.

Right now, the homepage is a lot to take in, so simplifying that could be a place where you could greatly help out. It's actually just straight up HTML5/CSS, so a designer's touch would be killer. We want to get creative here.

I will follow up soon with new information, after we have an internal discussion on this issue tomorrow.

We want your help! :+1: Stay tuned :)
