### ISSUE TITLE
Filters in main activity feed and Events do not work

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#152]
Two issues reported by the FOSSIL team:

* The filtering mechanism on the events page does not work. Changing the values in the drop down menus will blank the page and nothing else happens. The only way to get the listing of events back is to select 'events' again from the top menu.

* The drop down filter on my main page does not seem to filter at all. Changing the 'showing…' always returns the same elements in the list.

**Comment by epoirier** [comment]
This appears to be a problem again.  Changing "Showing..." does not update the activity stream.

**Comment by woodb** [comment]
@epoirier, with the removal of this feature, I'm closing this one out...
