### ISSUE TITLE
Uploading images from phone does not work

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#154]

**Comment by woodb** [comment]
Hey @epoirier, could you please elaborate on this issue? Is it possible that the user is not logged in on their phone?

**Comment by epoirier** [comment]
### Environment
* Signed in with my account (@epoirier) 
* iPhone 6, iOS 8.1.3
* Tested in Safari and Chrome

### Steps to Reproduce
1. In Fossil creation form, tap "Manage Images"
1. Tap "Upload Images"
1. Select image for upload, tap "Done"


### Observations
#### Safari and Chrome
* Sometimes the progress bar container appears, but no progress is shown and the page eventually reloads.  The "Upload Images" button is displayed without any images.

#### Chrome Only
* Sometimes the progress bar container appears, but no progress is shown, a spinning wheel in the status bar indicates internet activity but the page never reloads.

#### Safari Only

* The progress bar appears, but only gets half way through updating when the page reloads with the "Upload Images" button and no images.

**Comment by epoirier** [comment]
It appears this issue is more general.  Just ran into the same problem with the FOSSIL team trying to upload images from their laptops.

**Comment by woodb** [comment]
@epoirier can we mark this one as closed?
