### ISSUE TITLE
Feature needed to allow users to find eachother

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#156]
From the FOSSIL team:

* How do I find and add friends? I don't see a search field or other mechanism. I can see my existing friendships. I found how to see users--by going to my profile, clicking on my own name, then clicking the All Members tab (which is already selected). I then have to navigate to each person’s page in order to befriend them. This is very circuitous. It needs to be more straightforward.

**Comment by epoirier** [comment]
The members list is now visible.  If possible for v0.5.0, add a way to filter by name.

**Comment by woodb** [comment]
@epoirier here's how it looks...

![image](https://cloud.githubusercontent.com/assets/1631487/9289655/0cb97c3e-4346-11e5-81f8-36922cfae5a8.png)

![image](https://cloud.githubusercontent.com/assets/1631487/9289659/156a3da0-4346-11e5-8efb-85d729f218e2.png)
