### ISSUE TITLE
Add additional fields to user profile

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#162]
Add the following input fields to the user profile:

* About (describe yourself in a few short sentences)
* Fossil specialty (if any)
* Favorite collecting site(s) or region(s) (if any)
* Affiliations and Relevant Organizations
* Facebook
* Twitter
* Instagram
* Flickr
* LinkedIn
* Website

**Comment by woodb** [comment]
These have been added to the site that is newly hosted on WPEngine.

Because this is a database only feature, no code was required.

![image](https://cloud.githubusercontent.com/assets/1631487/6997690/f7a50f3a-db93-11e4-977c-a39920a84f57.png)

**Comment by woodb** [comment]
![image](https://cloud.githubusercontent.com/assets/1631487/6997696/2a9ad73a-db94-11e4-9042-ebf4be98bafe.png)
