### ISSUE TITLE
Posting comments is not working from within the activity feed

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#169]
Posting  a comment within the main activity feed results in an error at the top of the page that says "Please do not leave the comment area blank."

Steps to reproduce:

1. Type text into a comment field.
2. Tap "Post".

Result: The above error will be displayed and the comment will not appear.

**Comment by mikolaj89** [comment]
I can't reproduce this bug on my local enviroment (comments added correctly with AJAX).

**Comment by epoirier** [comment]
Can you look at it on the live site and see if you can determine the problem?

**Comment by epoirier** [comment]
Closing since it is the same as #172 which @shanebp is working on.
