### ISSUE TITLE
"WHEN" filter in Events is formatted incorrectly

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#170]
In Resources / Events the dates that appear in the "WHEN" select list are formatted incorrectly.

![image](https://cloud.githubusercontent.com/assets/643301/8993733/a7f59fd0-36d4-11e5-9338-4d93a8799e28.png)

**Comment by mikolaj89** [comment]
I cannot reproduce this bug on my localhost. Are You sure that correct year values are entered for these events ?

**Comment by mikolaj89** [comment]
It seems that dropdown works fine, and entered year values in db are like 0131, 1115, 1118 (look at the generated html source code for <option> tag)
