### ISSUE TITLE
Manually added pages are not styled

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#171]
The FOSSIL team needs to move all of the news letters from the old site to the new one.  However, the pages are not formatting properly.  For example, here is a page from the existing site:

http://www.myfossil.org/featured-organization-southwest-florida-fossil-society/

Here is how that page looks on the new site:

http://myfossil.wpengine.com/test/

**Comment by mikolaj89** [comment]
Are there "types" of newsletter pages on http://www.myfossil.org ? As a see there is no single common pattern applied to all newsletter pages, so the one template page for manually added pages in wp won't be enough( if they need exactly same look of particular pages as on http://www.myfossil.org/). On the other hand, in wordpress dashboard You can format every page manually, including positioning, paragrahps, indends, fonts, picutres etc.

**Comment by mikolaj89** [comment]
I think it looks more similar now
