### ISSUE TITLE
Unable to post reply via "post" button to a comment in the activity feed

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#172]
As reported by FOSSIL team:

> Cannot post a reply (via “Post” button) to a comment on your own wall → only get a red alert stating “Please do not leave the comment area blank”
>
> Can only post replies to comments on OTHER people’s walls

**Comment by epoirier** [comment]
Screenshot of the error message that appears after posting a comment:

![image](https://cloud.githubusercontent.com/assets/643301/9209355/11df79a2-4044-11e5-9c34-6fbe1f7536f5.png)

**Comment by shanebp** [comment]
If I post on my own wall, it works, but I get this javascript alert: 'test2'.  
So somebody is or was working on the javascript re posting updates. 
My hunch is that the issue you describe above is related to that javascript work. 
So pausing re this issue and trying to tread softly...

**Comment by epoirier** [comment]
I think that alert is something that Mikolaj accidentally left behind when he committed his work for #167.  This issue was happening before he made that fix.

**Comment by shanebp** [comment]
Sez  Mikolaj:
> in my local enviroment post button works with no problem with ajax (main activity view, posting comments to the posts)

Argh,,,

**Comment by shanebp** [comment]
When the front page loads, the console shows this js error:
Uncaught TypeError: jq.cookie is not a function  buddypress.min.js?ver=4.2.2:1683

Mikolaj - can you take a look?
