### ISSUE TITLE
Profile image upload process is unclear

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#173]
To change a profile image a user navigates to the Profile tab, then selects "Change Profile Photo".  To upload an image, the user must click "Browse", then find the image.  After finding an image to upload, it is unclear that the user should click the "Upload Image" button.

**Comment by shanebp** [comment]
Changed upload template so that 'file name' is visible. 
Ready for review on staging.

**Comment by epoirier** [comment]
Something broke.  Ability to upload a photo is gone.

**Comment by epoirier** [comment]
![image](https://cloud.githubusercontent.com/assets/643301/9311815/debf8218-44e6-11e5-8faf-afafdad59f2d.png)

**Comment by shanebp** [comment]
It was working. And the staging file matches my local file. 
On screen /members/[XXX]/profile/change-avatar/
The js console now shows these errors:
Uncaught TypeError: Cannot read property 'replace' of undefined - underscore.min.js:5 
Uncaught TypeError: Cannot read property 'on' of undefined - webcam.min.js?ver=2.4.0-alpha:2

**Comment by shanebp** [comment]
This may be related to Brandon's update on staging of BP to BP 2.4.0-alpha - which of course is not stable or meant for anything except testing.

**Comment by shanebp** [comment]
BP was rolled back - errors persist.

**Comment by shanebp** [comment]
BP rolled back to 2.2.2.1
repo theme branch search-autofocus has the correct template overload - change-avatar.php

**Comment by epoirier** [comment]
Working again.
