### ISSUE TITLE
Low quality profile image in activity view vs. other views

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#175]
The profile image that appears in the activity feed is significantly lower quality than the profile image that appears in other locations, such as a user's wall.  See screenshots for examples:

Activity feed:

![image](https://cloud.githubusercontent.com/assets/643301/9204071/efedd2c8-4028-11e5-97b1-9c9dac911044.png)

Wall:

![image](https://cloud.githubusercontent.com/assets/643301/9204083/0057bebc-4029-11e5-9fec-993829ff4f3e.png)

**Comment by shanebp** [comment]
Home page was calling the thumb avatar. 
Now calls for full size.
Ready on staging.

**Comment by epoirier** [comment]
Looks good.  Closing.
