### ISSUE TITLE
Activity feed filter does not work

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#176]
Changing the settings of "Showing..." select list does not update the activity feed.  For example, changing the filter to "Comments" does not change the content of the activity feed to only show comments.

This is because the filter has been disabled due to unexpected behavior.  The unexpected behavior is that changing the filter settings in the activity view modifies content in other locations of the site (for example in the Fossil / Discussion view).  We either need to remove the activity feed filter, or make it work only in the activity feed.

**Comment by shanebp** [comment]
Note to myself - this is probably due to how Fossil / Discussion was built.  Look there first.

**Comment by shanebp** [comment]
Eric - due to Friday deadline, the easy temp solution is to remove the dropdown from the UI. 

>...changing the filter settings in the activity view modifies content in other locations of 
>the site (for example in the Fossil / Discussion view)

To properly troubleshoot, I'd need to see exactly how the content is modified, iow. turn the filters back on. 
Or perhaps you could clarify?

Or we can just go with the temp solution and circle back later. 
Having a working activity feed filters is important as the activity entries pile up.

**Comment by epoirier** [comment]
Let's go with the temp solution and circle back later.  The temp solution is:
* Disable the activity filter
* Limit activity to only friends (not all activity)

**Comment by shanebp** [comment]
So the front page should only show activity generated by the logged-in user and their friends?

**Comment by epoirier** [comment]
Yes

**Comment by shanebp** [comment]
Ready for review.  
Also check Profile > Activity which should not have changed.

**Comment by shanebp** [comment]
Front page should now show activities for both logged-in user and their friends.

>I’d like to update the behavior so that the initial field in the activity feed posts to the logged-in user’s wall and appears below in the activity feed. 

It will post to the user's personal activity stream. But 'wall' is separate and only shows items specific to 'wall'.

**Comment by epoirier** [comment]
Looks good.
