### ISSUE TITLE
Remove links for "Name", "Fossil Specialty", and "Favorite Collecting Site(s)" in the user profile

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#178]
The Name, Fossil Specialty and Favorite Collecting Site(s) attributes in a user's profile are automatically converted to links to the Members view.  Please disable these links and display as text only.

![image](https://cloud.githubusercontent.com/assets/643301/9204400/15791b0e-402b-11e5-9947-408beea6a332.png)

**Comment by shanebp** [comment]
Typically, it's easier to  kill all links.
Then add link-ability to specific fields - in this case only 'website' ?

**Comment by epoirier** [comment]
Ok

**Comment by shanebp** [comment]
Done.
