### ISSUE TITLE
Update Members view to display number of published fossils

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#179]
The Members page currently displays "0" for all members.

![image](https://cloud.githubusercontent.com/assets/643301/9205290/433e1bc6-402f-11e5-9461-c636950f8e69.png)

**Comment by shanebp** [comment]
Fixed.  
Function in: \myfossil-theme\functions.php
Call in: \myfossil-theme\buddypress\members\members-loop.php

**Comment by epoirier** [comment]
It seems the number appearing is the total number of fossils entered by a user instead of the number of published fossils.  Tested by unpublishing the only fossil for user epoirier.test and reloading the Members page.  My user continued to show 1 fossil instead of 0.

**Comment by shanebp** [comment]
Sorry, easy fix.
Ok now?

**Comment by epoirier** [comment]
Now I'm seeing all zeros.

![image](https://cloud.githubusercontent.com/assets/643301/9253565/6eed37ec-41ac-11e5-920f-5946158fa3a8.png)

**Comment by shanebp** [comment]
Fixed.
