### ISSUE TITLE
Improve styling of forums

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#187]
Please improve styling of the forums to use the standard margins, font sizes, and other attributes as other parts of the myFOSSIL site.

**Comment by epoirier** [comment]
You can see forums on the staging site:
http://myfossil.staging.wpengine.com/forums/

**Comment by epoirier** [comment]
Uploaded latest commit.  Looking good so far.  Here's some feedback:

Test page can be viewed here:

http://myfossil.staging.wpengine.com/?page_id=875

I'm comparing with this:

http://www.myfossil.org/featured-organization-southwest-florida-fossil-society/

* Need to add the page title
* The `<em>` tag needs to be styled as italics
* The image table needs to be improved (Can you just use the same table styling that they are using in the above linked article?)

**Comment by mikolaj89** [comment]
Page title - do you mean gold header like "club corner: southwest florida fossil society" ? It's already styled, admin just need to enter header in dashboard page editor. Or should it always appear by default and use page title ?

**Comment by epoirier** [comment]
For news articles the page title should appear as a header.
