### ISSUE TITLE
Add ability to edit activity posts

### ISSUE THREAD

**Issue by shanebp** [myfossil/myfossil-theme#188]

**Comment by shanebp** [comment]
BP doesn't support editing of activity posts.

There's only one current plugin that allows such editing. 

Tried this plugin: https://wordpress.org/plugins/buddypress-edit-activity/
It does not work and throws these notices: 

<b>Notice</b>:  bbp_setup_current_user was called <strong>incorrectly</strong>. The current user is being initialized without using $wp->init(). Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 2.3.) in <b>/nas/wp/www/staging/myfossil/wp-includes/functions.php</b> on line <b>3560</b><br />
<br />
<b>Notice</b>:  bp_setup_current_user was called <strong>incorrectly</strong>. The current user is being initialized without using $wp->init(). Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 1.7.) in <b>/nas/wp/www/staging/myfossil/wp-includes/functions.php</b> on line <b>3560</b><br />
<br />
<b>Notice</b>:  Indirect modification of overloaded property BuddyBoss_Edit_Activity::$data has no effect in <b>/nas/wp/www/staging/myfossil/wp-content/plugins/buddypress-edit-activity/includes/main-class.php</b> on line <b>94</b><br />

Should be fixable..

But first, #181 needs to be fixed.

**Comment by epoirier** [comment]
Closing for now since this is standard behavior.  If it becomes an issue that is requested, then I'll reopen.
