### ISSUE TITLE
Activity entries are double posting

### ISSUE THREAD

**Issue by shanebp** [myfossil/myfossil-theme#189]
When creating an activity post from either front page or your wall, the entry is duplicated. 
This may be related to how the wall was built and whether the js / ajax was customized. 

mikolaj89 - assigned to you for now in order to get your feedback. 
Any input appreciated.  Maybe a quick fix?

**Comment by epoirier** [comment]
@shanebp I can't reproduce the issue in my activity feed.  It is still happening on my wall.

**Comment by mikolaj89** [comment]
Fixed- problem caused by doubled script in wall page
