### ISSUE TITLE
Activity feed shows replies to comments as standalone comments as well as nested below the parent comment

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#191]
This is not a case of double-posting the same comment.  There is some logic that shows a comment reply alone with a "View Conversation" link, as well as the comment in its place as a reply.

I don't think this is useful, but maybe I'm not seeing/understanding case where this presentation would be useful.

![image](https://cloud.githubusercontent.com/assets/643301/9261254/ae63b54e-41da-11e5-8f0e-015357e6a7b4.png)

**Comment by shanebp** [comment]
Discussed with Eric - It's a feature, not a bug.  It makes more sense when a lot of members are creating activity entries. Then comments are not buried AND can be read in context via the 'View Conversation' link.  

This issue can be closed, afaik.

**Comment by woodb** [comment]
I agree w/ @shanebp
