### ISSUE TITLE
Add Documents section to site, make searchable

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#192]
The fossil team wants to add a location on the site where documents and resources are linked.  The Documents section should appear under the Resources menu.  It can be a simple page that links to other pages and media files.  Pages that are part of the Resources section should be searchable.

**Comment by shanebp** [comment]
So this would be an addition or extension of the current myfossils-resources plugin.  
How are documents added? What are they added too?

**Comment by epoirier** [comment]
Documents will just be WP pages, though they may also link to pdf, video, or other file types.  Only the WP pages would be included in search.

**Comment by shanebp** [comment]
Who can create WP document pages?  And how?  Via a profile tab?  Or the way Fossils are added? 
Brandon will have a much better handle on this. 
I could write a plugin / custom BP component - if Brandon is comfortable with me doing so 8ball:

**Comment by epoirier** [comment]
Only site admins can make docs via the WP admin panel.

**Comment by shanebp** [comment]
Ok, then it's easy.  
Create a *post* & assign it to a category ( Documents ? ).
Create a *page* called Documents and create a custom template for it.
The template will list linked Doc titles. 
And include a search box  for text searches within the post - but not any attachments.

**Comment by shanebp** [comment]
Ready for review.
Pushed to repo.

**Comment by epoirier** [comment]
Looks good.
