### ISSUE TITLE
Implement basic search in Fossils

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#195]
Requirements for searching fossils are described in the [myFOSSIL Search Requirements](https://docs.google.com/document/d/1vLMboIsX-qgplycxMjvFviHUSK115j03xwCtAZ3ckqo/edit) Google Doc.

**Comment by woodb** [comment]
![image](https://cloud.githubusercontent.com/assets/1631487/9295234/6a6ae20c-4434-11e5-9391-a58cd26f452a.png)

![image](https://cloud.githubusercontent.com/assets/1631487/9295235/729364fe-4434-11e5-870e-e10658f82718.png)

![image](https://cloud.githubusercontent.com/assets/1631487/9295237/78935936-4434-11e5-9230-56da3c6814fc.png)

![image](https://cloud.githubusercontent.com/assets/1631487/9295238/7e59c99a-4434-11e5-82d6-caa210487b18.png)

![image](https://cloud.githubusercontent.com/assets/1631487/9295239/86c2773a-4434-11e5-8341-bd925d8eb1f1.png)
