### ISSUE TITLE
Top nav not appearing on category pages

### ISSUE THREAD

**Issue by shanebp** [myfossil/myfossil-theme#197]
Go to http://myfossil.staging.wpengine.com/documents/ and link one of the category links on the right side. 

Note that this template: */wp-content/themes/myfossil/archive.php* does not show the top nav links. 
I believe this is because */wp-content/themes/myfossil/header.php* expects all pages to be BuddyPress  pages. 

You may also want to format archive.php and only show excerpts for each listing.

**Comment by shanebp** [comment]
This seems to be working now.  Can someone confirm?

**Comment by epoirier** [comment]
Not seeing it on either staging or live.  After clicking one of the category links on the right I do not see the nav menu.

**Comment by shanebp** [comment]
Please test again on staging. ( this was also an issue in the footer nav )

**Comment by epoirier** [comment]
I see the nav.
