### ISSUE TITLE
Paragraph content is always bold

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#203]
Normal text is bold across the whole site.  Please change to standard weight.

E.g., Comments are bold, should be normal weight.

<img width="967" alt="screen shot 2015-08-17 at 1 40 22 pm" src="https://cloud.githubusercontent.com/assets/643301/9311663/b04dda84-44e5-11e5-86a4-d6a729b995d0.png">

This entire document text is bold.

<img width="1200" alt="screen shot 2015-08-17 at 1 42 24 pm" src="https://cloud.githubusercontent.com/assets/643301/9311685/e070288e-44e5-11e5-9de5-81cb0bb9f613.png">

**Comment by mikolaj89** [comment]
Eric - check on You Mac Book Pro if last commit solved a problem

**Comment by epoirier** [comment]
This seems to be some quirky thing with my environment. Closing.
