### ISSUE TITLE
Mentions auto-suggest feature not working on wall or activity feed

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#205]
Mentions (@ followed by a user name) stopped working in the main activity feed and wall.  The feature does work in the activity tab of the user's page.

Not working in activity feed:

![image](https://cloud.githubusercontent.com/assets/643301/9321191/2b694c9e-4531-11e5-9780-d3dc699d7e68.png)

Working in activity tab of user's page:

![image](https://cloud.githubusercontent.com/assets/643301/9321204/54f6c686-4531-11e5-8cfa-e7c2be0c3c38.png)

**Comment by shanebp** [comment]
Are you seeing this on staging?  
On staging, it only works in the Comment form on personal activity.
Does not work in Wall > Comment
Does not work in Post form.

**Comment by epoirier** [comment]
Yes, this is what I'm seeing.  Works this way on both staging and live.

**Comment by shanebp** [comment]
This now works on all activity pages and wall - but suggestions are not formatted properly. 

I'm enqueueing the JS files directly from [theme] functions.php in myfossil_scripts(). 
But this does not feel like a proper solution. 

@mikolaj89  - could the formating be due to missing css?

**Comment by shanebp** [comment]
Formatting seems okay now. 
Again - I'm loading css in [theme] functions.php in myfossil_scripts() - specifically /static/css/bp-activity-mentions.min.css
