### ISSUE TITLE
Add additional fields to User Profile

### ISSUE THREAD

**Issue by woodb** [myfossil/myfossil-theme#21]
![image](https://cloud.githubusercontent.com/assets/1631487/4877236/056ba028-62e2-11e4-8c63-3523e4161631.png)

**Comment by woodb** [comment]
Add the fields:
- Location (free form, single text input)
- Bio (textarea)
- Twitter (text inputs)
- Facebook (text inputs)
- LinkedIn (text inputs)

**Comment by epoirier** [comment]
This is done.
