### ISSUE TITLE
Location field repeats first value if unset

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#211]
It appears the location field for all members on a page is displaying the first value when the location is not set. 

![image](https://cloud.githubusercontent.com/assets/643301/9332938/2cfe3f60-4595-11e5-8026-c7fb8465b690.png)

![image](https://cloud.githubusercontent.com/assets/643301/9332949/38678cf8-4595-11e5-9ff5-e02671eefad9.png)

**Comment by shanebp** [comment]
This is on staging?  What browser?  I'm not see it here.
![member-location](https://cloud.githubusercontent.com/assets/1823937/9333238/a8910ea4-457d-11e5-8e0f-f524459c4e86.jpg)

**Comment by shanebp** [comment]
Check again now, please.

**Comment by epoirier** [comment]
This was on the live site, not staging.  Deploying now...

**Comment by epoirier** [comment]
Still an issue.

http://myfossil.wpengine.com/members/

![image](https://cloud.githubusercontent.com/assets/643301/9333988/6e247acc-459a-11e5-964f-e77d2470f018.png)

**Comment by shanebp** [comment]
What did you deploy?  Try the members-loop.php from staging.

**Comment by epoirier** [comment]
I used the WPEngine deploy control panel.  I just downloaded `members-loop.php` from both staging and live and diffed.  There are no differences.  

![image](https://cloud.githubusercontent.com/assets/643301/9334679/eb68a622-459d-11e5-8759-7f3b348424f1.png)

**Comment by shanebp** [comment]
Sry, but that image doesn't show the relevant area - which is just below where the img cuts off.

**Comment by shanebp** [comment]
This is what I see on Live:
![live-members](https://cloud.githubusercontent.com/assets/1823937/9335080/e9ff59fa-4586-11e5-8de7-155a56001fe6.jpg)

**Comment by shanebp** [comment]
This is now working on both staging and live. 
The 'fix' was to turn off wp.engine caching. 
I think the issue is that wp.engine caches a query and serves the result when BP makes an ajax call for a new query from the same 'location' - in this case members-loop sort

There are caching plugins we could use that are more tune-able. 
Eric may talk to wp.engine support about this.
