### ISSUE TITLE
Clicking "Uncategorized" in Documents produces many errors

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#213]
![image](https://cloud.githubusercontent.com/assets/643301/9336916/23718708-45aa-11e5-9e28-abfbd2706e2e.png)

**Comment by shanebp** [comment]
Tough one...
I programmatically created a new category call 'Misc'. 
If a document is not assigned to a category or is assigned to 'Uncategorized', it will be assigned to 'Misc' on save or update of the post. 

To see on Live, you need to get the latest myfossil_documents from git.
And deactivate / reactivate the plugin.

**Comment by epoirier** [comment]
Looks good.
