### ISSUE TITLE
Groups view is not paginating properly

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#218]
It appears the Groups view is counting hidden groups when paginating.  It should only display groups that are visible to the logged-in user and paginate accordingly.

![image](https://cloud.githubusercontent.com/assets/643301/9527841/641efa12-4cbf-11e5-9821-fc6d6a6cbfc1.png)

**Comment by shanebp** [comment]
If you are logged in as a site admin, the pagination and group count will include all groups - hidden included. 

If you are not logged in or logged in as an Author, the pagination and group count will  NOT include hidden groups.

This is normal behavior for site admins - do you want me to try and change it? 

btw - 17 site admins ! ? !

**Comment by epoirier** [comment]
Makes sense.  No, let's not change this.  

I have site admins down to 16.  Still working on getting it reduced further.
