### ISSUE TITLE
Forum mentions do not populate the "Mentions" list in the user section

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#219]
From a FOSSIL team member:

> I mentioned Chuck Ferrara (@cferrara) in a Forum topic, but it isn't showing up in Chuck's profile mention "list" [see pictures for reference].

![image](https://cloud.githubusercontent.com/assets/643301/9555404/d219d902-4d9a-11e5-8847-de17d26770e8.png)

![image](https://cloud.githubusercontent.com/assets/643301/9555408/d8c39860-4d9a-11e5-9dd1-85c880cb5fff.png)

**Comment by shanebp** [comment]
This issue only exists on staging. 
Works fine on dev.myfossil.org. You should see a mention I gave you in Help Forum. 

The issue on staging is that in wp-admin > Settings > Reading > Search Engine Visibility cannot be deselected. And that prevents forum mentions from generating activity entries.
