### ISSUE TITLE
Update link structure in global footer

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#222]
The global footer is currently listing all links that appear in the site menu on a single line.  The problem is that the menu includes nested content (currently under Resources).  Displaying all footer links on a single line does not communicate the hierarchy of the links that provided in the menu.  Also, the parent items in the menu are linked, but don't go to anything useful (E.g., Resources).  Please change the site footer that any menu item that has children is displayed as a nested unordered list, with the parent item unlinked.

Screenshot of current footer links:

![image](https://cloud.githubusercontent.com/assets/643301/9588748/ede96f8a-4ff7-11e5-9a8c-f06827099d5c.png)

**Comment by shanebp** [comment]
Ready for review.
