### ISSUE TITLE
Disable current events feature, add tribe events calendar

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#224]
The calendar needs to have the "Near Location" filter enabled.

https://theeventscalendar.com/product/wordpress-events-calendar/?source=tri.be

![image](https://cloud.githubusercontent.com/assets/643301/9588847/95698dee-4ff8-11e5-948e-ca3c58b4b975.png)

**Comment by shanebp** [comment]
Where is the Calendar appearing? 
Or has it not yet been installed ? 
It may be a premium plugin -  can you confirm?

The Events code is part of the Resources plugin. So it is mixed in with the Places code. 
Perhaps Brandon should handle any disabling.

**Comment by epoirier** [comment]
The Calendar app isn't installed yet.  Can we get away with not disabling Events in the resources plugin and still install the calendar and make the "Events" link in the menu point to the calendar?

**Comment by shanebp** [comment]
Should be able to adjust the Events link without disabling the resources plugin, but proof is in the pudding.

**Comment by shanebp** [comment]
Calendar plugin, free version, installed on staging.  Menu adjusted via wp-admin without disabling resources plugin.
