### ISSUE TITLE
Activity feed incorrectly attributes changes to the wrong fossil

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#233]
A user made changes to their own fossil, but the changes are being displayed as if they were made to another user's fossil in the activity feed. 

![image](https://cloud.githubusercontent.com/assets/643301/9858616/b016a58a-5aef-11e5-956a-9d2c975b429b.png)

Here's what's appearing in the activity feed for this fossil:

![image](https://cloud.githubusercontent.com/assets/643301/9858675/021e698a-5af0-11e5-8000-b3536bf5cbfd.png)

**Comment by epoirier** [comment]
You can see what this fossil looked like prior to the edits on the staging server.

![image](https://cloud.githubusercontent.com/assets/643301/9858716/32e17ddc-5af0-11e5-839a-5020b9814a17.png)

**Comment by epoirier** [comment]
@woodb Any word on this?

**Comment by woodb** [comment]
Closed with https://github.com/myfossil/myfossil-specimen/commit/2fe95efd50127d3f2bb9a6a3d29c3a956420bf1f
