### ISSUE TITLE
No message on successful password reset

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#248]
After a user successfully resets their password a screen appears that contains the myFOSSIL logo and a "Back to myFOSSIL" link.  Is there a standard message that can appear here that informs the user their update was successful and provides a link to the login form?

![image](https://cloud.githubusercontent.com/assets/643301/10282883/12abbfee-6b4b-11e5-95db-466e86d8c8a3.png)

**Comment by shanebp** [comment]
Should be an easy ticket, eh?  Nope.  
Finally had to talk to wpengine support. 
There may be a conflict with their required mu-plugin re strong passwords. 
WP-Engine Ticket #: 457249

**Comment by shanebp** [comment]
This was caused by a filter that was replacing all feedback messages with the logo.
I've commented out that filter and replaced it with a function that adds login css - the standard WP approach. 
A message now appears that informs the user their pw update was successful and provides a link to the login form.

**Comment by shanebp** [comment]
Miko - can you please check this on staging 
`function myfossil_custom_login_logo()` 
in
 `/wp-content/themes/myfossil/includes/filters.php`
and fix the css so that the logo image is displayed in the proper size?

**Comment by shanebp** [comment]
Mikolaj - forget the request re the logo function. 
I figured out an easy way to get the logo showing at the proper size. 

There is one minor issue - the login page shows double vertical scroll bars. 
I see them in Chrome and IE on a laptop. 
Perhaps this is not worth the effort - but if you know of a quick fix...
