### ISSUE TITLE
Change wording when a user follows a group

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#256]
The activity feed shows that a user "joined".  Please change this to "followed".

![image](https://cloud.githubusercontent.com/assets/643301/10338455/31d2e76e-6cd4-11e5-9b49-fe5ef8a6c040.png)

**Comment by shanebp** [comment]
Done. 
Added a filter function at the bottom.
File:  /wp-content/themes/myfossil/functions.php
