### ISSUE TITLE
Replying within notifications on a mention results in blank comment

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#257]
Reported by the FOSSIL team.  Here's a screenshot of the blank comment:

![image](https://cloud.githubusercontent.com/assets/643301/10350538/9c7a63ce-6d12-11e5-80aa-8b9173241767.png)

**Comment by shanebp** [comment]
Do we want to get this 'working' ? 
Beyond the blank comment... It seems like there is User confusion re what should show up & where.
And re Wall vs. Activity screens.

Or 'solve' it using the same approach as #254 ?

**Comment by epoirier** [comment]
I'm told they want to remove the wall completely.  Can you jump on a call?

**Comment by shanebp** [comment]
415.513.3997
