### ISSUE TITLE
Remove wall from site, add messaging feature to user activity profile tab

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#259]
Feature description documented in [Google Drive](https://docs.google.com/document/d/16hERl8pMGO_AWBpkKlgsLm6TA4Whh44MNiq7hX_61SY/edit).

**Comment by shanebp** [comment]
Ready for testing on staging.

I added Location data to member-header, where last-entry used to appear.

On home page,
I added 'mentions' to activity stream entries
and increased the # of entries shown to 30 - so maybe Load More is not necessary.

Changed files - All files in /wp-content/themes/myfossil/...

functions.php

buddypress/activity/left-menu.php
buddypress/activity/index.php
buddypress/activity/activity-loop.php
buddypress/activity/post-form.php

buddypress/members/single/member-header.php
buddypress/members/single/home.php

includes/plugins.php
includes/filters.php

**Comment by epoirier** [comment]
After posting a message to another user, the message appears in the user's activity feed.  The activity feed message also displays a comment input field below the message.  Can the comment input field be hidden?

![image](https://cloud.githubusercontent.com/assets/643301/10417580/f63c7ee8-700e-11e5-8c92-bc587aeb0e68.png)

**Comment by shanebp** [comment]
The comment input field appears whenever an entry is created in the Update form at the top of the page.  So not just for @ mentions. 

I believe it is exposed by ajax / js. 

I can try to remove that exposure for ALL situations where an Update entry is created.
