### ISSUE TITLE
Notification icon badged even when no notifications are present

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#262]
Reported via UserSnap:

![image](https://cloud.githubusercontent.com/assets/643301/11309602/c2e4d2f4-8f92-11e5-9134-5a185bed6db7.png)

**Comment by epoirier** [comment]
@shanebp Do you think this could be caused by the WPEngine object cache?

**Comment by shanebp** [comment]
Highly likely.  
Their cache is for WP. 
But BP is not as amenable to caching. 
I believe I turned it off at one point due to another issue.
But it was turned back on because... need to optimize Fossil queries due to current structure?

**Comment by epoirier** [comment]
Yep, it just randomly turns on anytime WPEngine does an update.  I'll contact them to see what it takes to make it stay off.

**Comment by epoirier** [comment]
I was able to do something different that is supposed to be more permanent,  closing for now.  Will repopen if it gets reported again.
