### ISSUE TITLE
Activity filters should be more granular

### ISSUE THREAD

**Issue by woodb** [myfossil/myfossil-theme#85]
The Activity filter of "Showing... [Everything]" dropdown could be more advanced, to allow for folks to filter out things like Group joins, etc. that may flood the feed. It's possible that people really will want granular access to view only the things that they're interested in.

Suggest something like checkboxes for the different types of Activities under a fancy dropdown, similar to GitHub's issues filters...

![image](https://cloud.githubusercontent.com/assets/1631487/4918952/db46cd16-64f5-11e4-94a8-da7228eb67ba.png)

**Comment by epoirier** [comment]
We've gotten rid of the filter.
